# Generated by Django 6.0.5 on 2026-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('anomaly_type', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_component', models.CharField(blank=True, max_length=255, null=True)),
                ('node', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_tier_from_llm', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_from_llm', models.FloatField(blank=True, null=True)),
                ('decision_type', models.CharField(max_length=50)),
                ('decision_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('time_in_queue_seconds', models.FloatField(blank=True, null=True)),
                ('original_actions', models.TextField(blank=True, null=True)),
                ('final_actions', models.TextField(blank=True, null=True)),
                ('operator_notes', models.TextField(blank=True, null=True)),
                ('auto_execute_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'decisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HitlIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], default='PENDING', max_length=20)),
                ('payload_json', models.TextField(help_text='Full Policy Agent message as JSON')),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['arrived_at'],
            },
        ),
    ]
