# Generated by Django 6.0.5 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hitlincident",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
